version: '3'

services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true

volumes:
  node_modules: