name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "src/package-lock.json"

      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            src/.next/cache
            src/node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('src/package-lock.json') }}-${{ hashFiles('src/**/*.[jt]s', 'src/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('src/package-lock.json') }}-
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: npm ci
        working-directory: ./src

      - name: Build
        run: npm run build
        working-directory: ./src

      - name: Run lint
        run: npm run lint
        working-directory: ./src

      - name: Run tests
        run: npm test
        working-directory: ./src
